name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Install everything i need
        run: |
          sudo apt install python3.8
          python --version
          pip install checkov


      - name: run and save checkov output
        run:  |
          checkov -d . -o sarif | tee checkovtest.sarif
 
      - name: upload sarif results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'checkovtest.sarif'

  
  trivy-Config-job:
    runs-on: ubuntu-18.04
    name: trivy image scanning
    steps:          
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Build an image from Dockerfile
        run: |
          docker build ./pythonwebapp --tag flask-demo-container:${{ github.sha }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-demo-container:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
  
          
        
        
