name: Checkov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Install everything i need
        run: |
           - apk add python3
           - apk add py3-pip
           - pip3 install pystache
           - python3 --version
           - pip3 install checkov


      - name: run and save checkov output
        if: ${{ always() }}
        run:  |
           - checkov -d . -o sarif > checkovoutput.sarif
           - cat checkovoutput.sarif
          
 
      - name: hi
        run: echo 'hi'
        
