name: NODE container CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Install everything i need
        run: |
          sudo apt install python3.8
          python --version
          pip install checkov
      - name: run and save checkov output
        run:  |
          checkov -d ./nodejs -o json
 
  trivy-build-scan:
    runs-on: ubuntu-18.04
    if: always()
    needs: checkov-job
    name: trivy image scanning
    steps:    
    
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Build an image from Dockerfile
        run: |
          docker build ./nodejs --tag node-demo-container:${{ github.sha }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'node-demo-container:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'report.sarif'
          
      - name: check files
        run: |
          ls
          cat report.sarif
          
      #- name: Upload Trivy scan results to GitHub Security tab
      #  if: always()
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: 'report.sarif'
          
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    if: always()
    name: Anchore image scanning
    needs: checkov-job
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Build an image from Dockerfile
      run: |
          docker build ./nodejs --tag node-demo-container:${{ github.sha }}
  
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@main
      with:
        image: "node-demo-container:${{ github.sha }}"
        acs-report-enable: true
        
